services:
  webapp:
    hostname: 'rtbdev'
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/home/rtbdev/code/:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started

  # reuse the db service from the root compose file, just reachable from the host
  db:
    ports:
      - "3306:3306"
